# Generated by Django 3.0.2 on 2020-05-31 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccount',
        ),
    ]
