# Generated by Django 3.0.2 on 2020-05-31 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200531_0341'),
        ('my_account', '0003_myaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaccount',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
    ]
