# Generated by Django 3.0.2 on 2020-05-31 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_account', '0004_myaccount_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myaccount',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='myaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
