# Generated by Django 3.0.2 on 2020-05-31 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0006_auto_20200531_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='user',
        ),
    ]
