# Generated by Django 3.0.2 on 2020-05-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_item_user'),
        ('my_account', '0008_myaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myaccount',
            name='item',
        ),
        migrations.AddField(
            model_name='myaccount',
            name='item',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
