# Generated by Django 3.0.2 on 2020-06-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
