# Generated by Django 3.0.2 on 2020-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200609_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, choices=[('C', 'Color'), ('S', 'Size')], max_length=100),
        ),
    ]
