# Generated by Django 3.0.2 on 2020-06-16 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200614_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together={('item', 'name', 'value')},
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='variation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
