# Generated by Django 3.0.2 on 2020-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200618_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
