# Generated by Django 3.0.2 on 2020-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_item_negotiable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='used',
        ),
    ]
