# Generated by Django 3.0.2 on 2020-06-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_item_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='phone_number',
            new_name='call_number',
        ),
        migrations.AddField(
            model_name='item',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
