# Generated by Django 3.0.2 on 2020-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200621_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to='media/images'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
