# Generated by Django 3.0.2 on 2020-07-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_quartier_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_category',
            field=models.BooleanField(default=False),
        ),
    ]
