# Generated by Django 3.0.2 on 2020-07-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20200720_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(max_length=3, upload_to='media/images'),
        ),
    ]
