# Generated by Django 3.0.2 on 2020-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20200721_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
