# Generated by Django 3.0.2 on 2020-08-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20200810_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
