# Generated by Django 3.0.2 on 2020-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20200810_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='call_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
