# Generated by Django 3.0.2 on 2020-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20201110_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
